TYPO3:
  TYPO3CR:
    contentTypes:
      'Planetflow3:MetablogPlugin':
        superTypes: ['TYPO3.TYPO3:Plugin']
        label: 'Metablog plugin'
        group: 'Plugins'
        properties:
          package:
            default: Planetflow3
          controller:
            default: Plugin
          action:
            default: items
          itemsPerPage:
            type: integer
            default: 10
            label: 'Items per page'
            category: 'pluginSettings'
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              provider: PersistedUsernamePasswordProvider
              entryPoint: 'WebRedirect'
              entryPointOptions:
                routeValues:
                  '@package': 'TYPO3.Planet'
                  '@controller': 'Login'
                  '@action': 'Index'
      authorization:
        allowAccessIfAllVotersAbstain: TRUE

Planetflow3:
  log:
    feedLogger:
      backendOptions:
        logFileURL: %FLOW_PATH_DATA%Logs/Planetflow3_Feed.log
        createParentDirectories: TRUE
        severityThreshold: %LOG_INFO%
        maximumLogFileSize: 1048576
        logFilesToKeep: 1
  frontend:
    view:
      template: NULL
