TYPO3:
  TYPO3CR:
    contentTypes:
      'Planetflow3:MetablogPlugin':
        superTypes: ['TYPO3.TYPO3:Plugin']
        label: 'Metablog plugin'
        group: 'Plugins'
        properties:
          package:
            default: Planetflow3
          controller:
            default: Plugin
          action:
            default: items
          itemsPerPage:
            type: integer
            default: 10
            label: 'Items per page'
            category: 'pluginSettings'
  Flow:
    object:
      excludeClasses:
        'simplepie.simplepie': ['.*']
    security:
      enable: TRUE
      #authorization:
        #accessDecisionVoters: [TYPO3\FLOW3\Security\Authorization\Voter\Policy]
        #allowAccessIfAllVotersAbstain: FALSE
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'TYPO3.Planet/Login/index'
              routeValues:
                '@package': 'TYPO3.Planet'
                '@controller': 'Login'
                '@action': 'index'
  Planet:
    log:
      feedLogger:
        backendOptions:
          logFileURL: %FLOW_PATH_DATA%Logs/Planetflow3_Feed.log
          createParentDirectories: TRUE
          severityThreshold: %LOG_INFO%
          maximumLogFileSize: 1048576
          logFilesToKeep: 1
    frontend:
      view:
        template: NULL
